global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: "booking-service"
    metrics_path: /metrics
    static_configs:
      - targets:
          - booking-service:8002

  - job_name: "auth-service"
    metrics_path: /metrics
    static_configs:
      - targets:
          - auth-service:8001

  - job_name: "flight-service"
    metrics_path: /metrics
    static_configs:
      - targets:
          - flight-service:8002